package com.cresensolutions.document_search_azure_indexing.utils;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.Base64;
import java.util.stream.Collectors;

/**
 * Common shared utility methods for Document Search Azure Indexing service.
 * Helps with null safety, JSON parsing, URL construction, string sanitization, and clean logging.
 */
@Slf4j
public final class CommonUtils {

    private CommonUtils() {
        // Prevent instantiation of utility class
    }

    /**
     * Checks if a string has non-whitespace characters.
     *
     * @param value the string to check
     * @return true if string is not null and contains non-whitespace text
     */
    public static boolean hasText(String value) {
        return value != null && !value.isBlank();
    }

    /**
     * Converts any object to a non-null string safely.
     *
     * @param value the object to convert
     * @return non-null string representation of the object (defaults to empty string)
     */
    public static String stringValue(Object value) {
        return value == null ? "" : value.toString();
    }

    /**
     * Returns a default fallback string if the target object converts to empty/null.
     *
     * @param value    the target object
     * @param fallback the default string value
     * @return clean string or the fallback default string
     */
    public static String defaultString(Object value, String fallback) {
        String text = stringValue(value);
        return text.isBlank() ? fallback : text;
    }

    /**
     * Standardizes all whitespaces, replaces multiple consecutive whitespaces with a single space, and trims boundaries.
     * Useful for parsing clean text from noisy documents.
     *
     * @param value the string to sanitize
     * @return cleaned text with normalized spaces
     */
    public static String normalizeWhitespace(String value) {
        return value == null ? "" : value.replaceAll("\\s+", " ").trim();
    }

    /**
     * Trims any trailing slashes from the URL endpoints.
     *
     * @param value the URL endpoint
     * @return normalized URL without trailing slash
     */
    public static String trimTrailingSlash(String value) {
        if (value == null) {
            return "";
        }
        return value.endsWith("/") ? value.substring(0, value.length() - 1) : value;
    }

    /**
     * Extract clean JSON block from markdown wrapped code ticks generated by LLMs.
     *
     * @param content the raw LLM string containing optional json ticks
     * @return clean JSON object format ready to parse
     */
    public static String extractJsonObject(String content) {
        String text = content == null ? "" : content.trim()
                .replaceFirst("^```json\\s*", "")
                .replaceFirst("^```\\s*", "")
                .replaceFirst("\\s*```$", "");
        int start = text.indexOf('{');
        int end = text.lastIndexOf('}');
        if (start >= 0 && end > start) {
            return text.substring(start, end + 1);
        }
        return text;
    }

    /**
     * Parse raw content from LLM markdown into concrete DTO model class using ObjectMapper.
     *
     * @param rawContent   the raw JSON or Markdown string returned by the LLM
     * @param targetClass  the destination DTO/Model class type
     * @param objectMapper Jackson mapper
     * @param <T>          model type
     * @return mapped class instance
     * @throws JsonProcessingException if Jackson mapping fails
     */
    public static <T> T parseLlmJson(String rawContent, Class<T> targetClass, ObjectMapper objectMapper) throws JsonProcessingException {
        if (!hasText(rawContent)) {
            throw new IllegalArgumentException("Cannot parse empty LLM content");
        }
        String json = extractJsonObject(rawContent);
        return objectMapper.readValue(json, targetClass);
    }

    /**
     * Parses the pure filename from a standard storage relative or fully-qualified blob path.
     *
     * @param blobName relative path or full URL
     * @return clean local filename
     */
    public static String filename(String blobName) {
        int slash = blobName == null ? -1 : blobName.lastIndexOf('/');
        return slash >= 0 ? blobName.substring(slash + 1) : stringValue(blobName);
    }

    /**
     * Generates a random alphanumeric UUID string without hyphens.
     *
     * @return clean uuid string
     */
    public static String simpleUuid() {
        return UUID.randomUUID().toString().replace("-", "");
    }

    /**
     * Extracts the file extension (lowercase) from a filename or path.
     *
     * @param filename the file name or path
     * @return the file extension without dot, or empty string if none
     */
    public static String fileExtension(String filename) {
        if (filename == null || !filename.contains(".")) {
            return "";
        }
        return filename.substring(filename.lastIndexOf('.') + 1).toLowerCase();
    }

    /**
     * Generates SHA-256 hash of a text string.
     *
     * @param content content to hash
     * @return hex representation of the SHA-256 hash
     */
    public static String sha256(String content) {
        if (content == null) {
            return "";
        }
        try {
            java.security.MessageDigest digest = java.security.MessageDigest.getInstance("SHA-256");
            return java.util.HexFormat.of().formatHex(digest.digest(content.getBytes(java.nio.charset.StandardCharsets.UTF_8)));
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 algorithm not found", e);
        }
    }

    /**
     * Base64URL-encodes a string safely, removing padding.
     *
     * @param value standard text string
     * @return Base64URL encoded version without padding
     */
    public static String base64UrlEncode(String value) {
        if (value == null) {
            return "";
        }
        return Base64.getUrlEncoder()
                .withoutPadding()
                .encodeToString(value.getBytes(java.nio.charset.StandardCharsets.UTF_8));
    }
}
